services:
  app:
    build: .
    # command: /bin/sh surf-tg.sh  <-- We might need to bypass this if it forces updates
    restart: on-failure
    volumes:
      - .:/app  # This syncs your PC files to the container in real-time
    environment:
      - PYTHONUNBUFFERED=1
      - UPSTREAM_REPO=          # Setting this to empty stops the code overwrite
      - UPSTREAM_BRANCH=        # Clear this too
    ports:
      - "8080:8080"
  addon:
    build: .
    restart: on-failure
    volumes:
      - .:/app
    command: python test.py
    ports:
      - "7000:7000"
    depends_on:
      - app